services:
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
